create table ShippingAddress (
	id INT,
	state VARCHAR(50),
	city VARCHAR(50)
);
insert into ShippingAddress (id, state, city) values (1, 'Texas', 'El Paso');
insert into ShippingAddress (id, state, city) values (2, 'Maryland', 'Rockville');
insert into ShippingAddress (id, state, city) values (3, 'Indiana', 'Indianapolis');
insert into ShippingAddress (id, state, city) values (4, 'Wisconsin', 'Madison');
insert into ShippingAddress (id, state, city) values (5, 'Missouri', 'Columbia');
insert into ShippingAddress (id, state, city) values (6, 'Texas', 'San Antonio');
insert into ShippingAddress (id, state, city) values (7, 'Texas', 'Temple');
insert into ShippingAddress (id, state, city) values (8, 'Pennsylvania', 'Pittsburgh');
insert into ShippingAddress (id, state, city) values (9, 'Texas', 'Mesquite');
insert into ShippingAddress (id, state, city) values (10, 'Connecticut', 'Bridgeport');
insert into ShippingAddress (id, state, city) values (11, 'Massachusetts', 'Newton');
insert into ShippingAddress (id, state, city) values (12, 'Washington', 'Yakima');
insert into ShippingAddress (id, state, city) values (13, 'California', 'North Hollywood');
insert into ShippingAddress (id, state, city) values (14, 'California', 'San Rafael');
insert into ShippingAddress (id, state, city) values (15, 'Washington', 'Tacoma');
insert into ShippingAddress (id, state, city) values (16, 'California', 'Orange');
insert into ShippingAddress (id, state, city) values (17, 'Texas', 'San Antonio');
insert into ShippingAddress (id, state, city) values (18, 'California', 'Sacramento');
insert into ShippingAddress (id, state, city) values (19, 'Illinois', 'Chicago');
insert into ShippingAddress (id, state, city) values (20, 'Kentucky', 'Migrate');
insert into ShippingAddress (id, state, city) values (21, 'California', 'San Diego');
insert into ShippingAddress (id, state, city) values (22, 'District of Columbia', 'Washington');
insert into ShippingAddress (id, state, city) values (23, 'Connecticut', 'Bridgeport');
insert into ShippingAddress (id, state, city) values (24, 'South Carolina', 'Greenville');
insert into ShippingAddress (id, state, city) values (25, 'Rhode Island', 'Providence');
insert into ShippingAddress (id, state, city) values (26, 'Texas', 'Gatesville');
insert into ShippingAddress (id, state, city) values (27, 'Tennessee', 'Memphis');
insert into ShippingAddress (id, state, city) values (28, 'Alabama', 'Huntsville');
insert into ShippingAddress (id, state, city) values (29, 'Idaho', 'Boise');
insert into ShippingAddress (id, state, city) values (30, 'California', 'Los Angeles');
insert into ShippingAddress (id, state, city) values (31, 'Oklahoma', 'Oklahoma City');
insert into ShippingAddress (id, state, city) values (32, 'Texas', 'Dallas');
insert into ShippingAddress (id, state, city) values (33, 'Tennessee', 'Memphis');
insert into ShippingAddress (id, state, city) values (34, 'Nevada', 'Henderson');
insert into ShippingAddress (id, state, city) values (35, 'South Carolina', 'Columbia');
insert into ShippingAddress (id, state, city) values (36, 'Virginia', 'Arlington');
insert into ShippingAddress (id, state, city) values (37, 'Texas', 'San Antonio');
insert into ShippingAddress (id, state, city) values (38, 'Texas', 'San Antonio');
insert into ShippingAddress (id, state, city) values (39, 'Nevada', 'Reno');
insert into ShippingAddress (id, state, city) values (40, 'New Jersey', 'Camden');
insert into ShippingAddress (id, state, city) values (41, 'Kentucky', 'Louisville');
insert into ShippingAddress (id, state, city) values (42, 'New Jersey', 'Newark');
insert into ShippingAddress (id, state, city) values (43, 'Minnesota', 'Minneapolis');
insert into ShippingAddress (id, state, city) values (44, 'Michigan', 'Kalamazoo');
insert into ShippingAddress (id, state, city) values (45, 'Alabama', 'Birmingham');
insert into ShippingAddress (id, state, city) values (46, 'Florida', 'Pensacola');
insert into ShippingAddress (id, state, city) values (47, 'Colorado', 'Colorado Springs');
insert into ShippingAddress (id, state, city) values (48, 'Florida', 'Largo');
insert into ShippingAddress (id, state, city) values (49, 'Texas', 'Gatesville');
insert into ShippingAddress (id, state, city) values (50, 'Connecticut', 'Hartford');
insert into ShippingAddress (id, state, city) values (51, 'California', 'Fresno');
insert into ShippingAddress (id, state, city) values (52, 'Texas', 'Amarillo');
insert into ShippingAddress (id, state, city) values (53, 'Mississippi', 'Biloxi');
insert into ShippingAddress (id, state, city) values (54, 'Texas', 'Dallas');
insert into ShippingAddress (id, state, city) values (55, 'Pennsylvania', 'Harrisburg');
insert into ShippingAddress (id, state, city) values (56, 'Kentucky', 'London');
insert into ShippingAddress (id, state, city) values (57, 'California', 'Sacramento');
insert into ShippingAddress (id, state, city) values (58, 'Massachusetts', 'New Bedford');
insert into ShippingAddress (id, state, city) values (59, 'Washington', 'Seattle');
insert into ShippingAddress (id, state, city) values (60, 'California', 'San Jose');
insert into ShippingAddress (id, state, city) values (61, 'Georgia', 'Valdosta');
insert into ShippingAddress (id, state, city) values (62, 'Kansas', 'Topeka');
insert into ShippingAddress (id, state, city) values (63, 'Washington', 'Olympia');
insert into ShippingAddress (id, state, city) values (64, 'Indiana', 'Fort Wayne');
insert into ShippingAddress (id, state, city) values (65, 'District of Columbia', 'Washington');
insert into ShippingAddress (id, state, city) values (66, 'Oklahoma', 'Tulsa');
insert into ShippingAddress (id, state, city) values (67, 'Oklahoma', 'Tulsa');
insert into ShippingAddress (id, state, city) values (68, 'District of Columbia', 'Washington');
insert into ShippingAddress (id, state, city) values (69, 'Florida', 'Tampa');
insert into ShippingAddress (id, state, city) values (70, 'North Carolina', 'Charlotte');
insert into ShippingAddress (id, state, city) values (71, 'Pennsylvania', 'Pittsburgh');
insert into ShippingAddress (id, state, city) values (72, 'West Virginia', 'Charleston');
insert into ShippingAddress (id, state, city) values (73, 'Florida', 'Saint Augustine');
insert into ShippingAddress (id, state, city) values (74, 'Tennessee', 'Nashville');
insert into ShippingAddress (id, state, city) values (75, 'Georgia', 'Savannah');
insert into ShippingAddress (id, state, city) values (76, 'Arizona', 'Tucson');
insert into ShippingAddress (id, state, city) values (77, 'Tennessee', 'Knoxville');
insert into ShippingAddress (id, state, city) values (78, 'California', 'Whittier');
insert into ShippingAddress (id, state, city) values (79, 'Louisiana', 'Baton Rouge');
insert into ShippingAddress (id, state, city) values (80, 'Kansas', 'Shawnee Mission');
insert into ShippingAddress (id, state, city) values (81, 'Minnesota', 'Young America');
insert into ShippingAddress (id, state, city) values (82, 'California', 'Los Angeles');
insert into ShippingAddress (id, state, city) values (83, 'Kentucky', 'Lexington');
insert into ShippingAddress (id, state, city) values (84, 'Maryland', 'Laurel');
insert into ShippingAddress (id, state, city) values (85, 'New York', 'Albany');
insert into ShippingAddress (id, state, city) values (86, 'Wisconsin', 'Milwaukee');
insert into ShippingAddress (id, state, city) values (87, 'Ohio', 'Cincinnati');
insert into ShippingAddress (id, state, city) values (88, 'New York', 'Albany');
insert into ShippingAddress (id, state, city) values (89, 'Florida', 'Zephyrhills');
insert into ShippingAddress (id, state, city) values (90, 'Tennessee', 'Chattanooga');
insert into ShippingAddress (id, state, city) values (91, 'Idaho', 'Idaho Falls');
insert into ShippingAddress (id, state, city) values (92, 'California', 'Salinas');
insert into ShippingAddress (id, state, city) values (93, 'Kentucky', 'Lexington');
insert into ShippingAddress (id, state, city) values (94, 'California', 'San Jose');
insert into ShippingAddress (id, state, city) values (95, 'Nebraska', 'Omaha');
insert into ShippingAddress (id, state, city) values (96, 'Georgia', 'Valdosta');
insert into ShippingAddress (id, state, city) values (97, 'Texas', 'Abilene');
insert into ShippingAddress (id, state, city) values (98, 'Illinois', 'Joliet');
insert into ShippingAddress (id, state, city) values (99, 'Alaska', 'Anchorage');
insert into ShippingAddress (id, state, city) values (100, 'Iowa', 'Des Moines');
